# Generated by Django 3.2.5 on 2021-12-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Colaborador', models.IntegerField()),
                ('Nom_Colaborador', models.CharField(max_length=70)),
                ('Rol', models.CharField(max_length=50)),
                ('Carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Distribuidor', models.IntegerField()),
                ('Nom_Distribuidor', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Producto', models.IntegerField()),
                ('Nom_Producto', models.CharField(max_length=100)),
                ('Precio', models.FloatField()),
                ('Unidades', models.IntegerField()),
                ('Caracteristicas', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Venta', models.IntegerField()),
                ('Precio', models.FloatField()),
                ('Unidades', models.IntegerField()),
                ('Total', models.FloatField()),
                ('Fecha_Ven', models.DateField()),
                ('Nom_Distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.distribuidor')),
                ('Nom_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unidades', models.IntegerField()),
                ('Fecha_Reg', models.DateField()),
                ('Total', models.IntegerField()),
                ('No_Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.venta')),
                ('Nom_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.tipoproducto'),
        ),
        migrations.CreateModel(
            name='Devolución',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Causa', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=50)),
                ('Fecha_Dev', models.DateField()),
                ('Nom_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.producto')),
            ],
        ),
    ]
