# Generated by Django 3.2.5 on 2021-12-12 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaCanelita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolución',
            name='No_Venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.venta'),
        ),
        migrations.AlterField(
            model_name='devolución',
            name='Nom_Producto',
            field=models.CharField(max_length=100),
        ),
    ]
