# Generated by Django 3.2.5 on 2021-12-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaCanelita', '0002_auto_20211211_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_venta',
            name='Nom_Producto',
            field=models.CharField(max_length=100),
        ),
    ]
