# Generated by Django 3.2.5 on 2021-12-12 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaCanelita', '0003_alter_registro_venta_nom_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='devolución',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaCanelita.estado'),
        ),
    ]
