# Generated by Django 3.2.5 on 2021-12-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaCanelita', '0004_auto_20211211_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
    ]
