# Generated by Django 3.2.5 on 2021-12-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaCanelita', '0005_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='Imagen_Col',
            field=models.ImageField(blank=True, upload_to='colaboradores/'),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='Imagen_Dis',
            field=models.ImageField(blank=True, upload_to='distribuidores/'),
        ),
    ]
